App7/urls.py
from django.contrib import admin   
from django.urls import path, include
from .views import Index, conf, delete

app_name = 'App7'

urlpatterns = [
    path('',Index, name = 'Index'),
    path('<int:pk>/', delete, name = 'delete'),
    path('confirmation/', conf, name = 'confirmation')
] 

Story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App7.urls')),
]

App7/models.py
from django.db import models

# Create your models here.
class App7Model(models.Model):
    name = models.CharField(max_length=30)
    message = models.CharField(max_length=200)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}"

    

App7/forms.py
from django import forms

class App7Form(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Name',
        'type' : 'text',
    }))
    message = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'message ',
        'type' : 'text',
    }))

App7/views.py
from django.shortcuts import render, redirect
from .models import App7Model
from .forms import App7Form

def Index(request):
    if request.method=="POST":
        frm = App7Form(request.POST)
        if frm.is_valid():
            frm2 = App7Model()
            frm2.name = frm.cleaned_data["name"]
            frm2.message= frm.cleaned_data["message"]
            frm2.save()
        return redirect("/confirmation")
    frm = App7Form()
    frm2 = App7Model.objects.all()
    frm_dictio = {
        'frm':frm, #form
        'frm2':frm2 #model/isi formnya
    }
    return render(request,'Index.html',frm_dictio)

def conf(request):
    msg_input = App7Model.objects.last()
    conf_dictio = {
        'msg_input': msg_input}
    return render(request, 'Conf.html',conf_dictio)

def delete(request, pk):
    if request.method == "POST":
        frm = App7Form(request.POST)
        if frm.is_valid():
            frm2 = App7Model()
            frm2.name = frm.cleaned_data["name"]
            frm2.message = frm.cleaned_data["message"]
            frm2.save()
        return redirect("/confirmation")
    else:
        App7Model.objects.filter(pk = pk).delete()
        frm = App7Form()
        frm2 = App7Model.objects.all()
        msg_dictio ={
            'frm' : frm,
            'frm2': frm2
        }
        return render(request, 'Index.html', msg_dictio)

App7/templates/Conf.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Are You Sure?</title>
    <link rel="stylesheet" type="text/css" href="{% static 'conf.css' %}">

</head>

<body>
    <div class="adj">
        <p class="r">Are You Sure?</p>
        <div class="teks">
            <ul style="list-style: none;">
                <li>{{msg_input.name}}</li>
                <li style="font-size: 20px;">"{{msg_input.message}}"</li>
            </ul>
        </div>
        <button><a class="btn btn-primary btn-lg" href="{% url 'App7:delete' pk=msg_input.pk %}" type="submit" role="button">No</a></button>
        <button><a class="btn light btn-lg" href="{% url 'App7:Index' %}" type="submit" role="button">Yes</a></button>
    </div>
</body>

</html>

App7/templates/Index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Story7</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <div class="form">
        <form action='' method="POST">
            {% csrf_token %}
            <ul style="list-style: none;">
                <li>Name <br>{{ frm.name }}</li>
                <br>
                <li>Message <br> {{ frm.message }}</li>
                <br>
                <button name="submit" type="submit" class="buttons">Submit</button>

            </ul>
        </form>
    </div>
    <div id=t ulisan>
        <h3>Messanges</h3>
        <div class="table">
            <table class="table1">
                {% for i in frm2%}
                <ul style="border-style: solid; border-color: white;list-style: none;border-width: thin;padding: 1em;">
                    <li>{{i.name}}</li>
                    <li>"{{i.message}}"</li>
                    <li style="font-size: 10px;">{{i.time}}</li>
                </ul>
                {% endfor %}
            </table>
        </div>
    </div>

</body>